apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-redirect-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: brunzema.com
    http:
      paths:
      - path: /redirect
        pathType: Prefix
        backend:
          service:
            name: flask-redirect-app-service
            port:
              number: 80
