apiVersion: v1
kind: Service
metadata:
  name: flask-redirect-app-service
spec:
  allocateLoadBalancerNodePorts: true
  selector:
    app: flask-redirect-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
